/* eslint-disable */
// Generated by Wrangler by running `wrangler types types/cloudflare-deployment.d.ts --config wrangler.cloudflare.jsonc --env-interface CloudflareDeploymentEnv --include-runtime false` (hash: e6a02d072be589b4cf817dead773beb0)
interface __BaseEnv_CloudflareDeploymentEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/server/index");
	}
	interface Env extends __BaseEnv_CloudflareDeploymentEnv {}
}
interface CloudflareDeploymentEnv extends __BaseEnv_CloudflareDeploymentEnv {}
